name: krona_text
owner: petr-novak
description: Krona visualization tool
long_description: Krona visualization tool
categories:
  - Visualization
remote_repository_url: https://github.com/kavonrtep/galaxy_packages
homepage_url: https://github.com/kavonrtep/galaxy_packages
